# Generated by Django 6.0.1 on 2026-02-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
