"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django.
Adapted for Render Deployment.
"""

import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# En producción lee la clave del entorno, en local usa la insegura por defecto
SECRET_KEY = os.environ.get('SECRET_KEY', default='django-insecure-*+bkb2t9q!1fdonspp6nt@6g(!-8grr9ss3)r$f@d(c&pkk2=f')

# SECURITY WARNING: don't run with debug turned on in production!
# Si estamos en Render, DEBUG será False. En tu PC será True.
DEBUG = 'RENDER' not in os.environ

ALLOWED_HOSTS = []

# Configuración automática para el dominio de Render
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',            # Para conectar con React
    'rest_framework',         # Django Rest Framework
    'rest_framework.authtoken',
    'api',                    # Tu aplicación principal (Instinto Parfums)
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # <--- SIEMPRE PRIMERO
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # <--- IMPORTANTE: Para estilos en Render
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Configuración Híbrida: SQLite (Local) vs PostgreSQL (Render)
DATABASES = {
    'default': dj_database_url.config(
        # Busca la variable DATABASE_URL en Render. Si no la halla, usa SQLite.
        default='sqlite:///db.sqlite3',
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Configuración de WhiteNoise para servir archivos estáticos en producción
if not DEBUG:
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Configuración de Archivos Multimedia (Imágenes de perfumes/ventas)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --- CONFIGURACIÓN CORS ---
# Permitimos todo para facilitar el despliegue inicial
CORS_ALLOW_ALL_ORIGINS = True 

# Si prefieres seguridad estricta más adelante, descomenta esto y comenta la línea de arriba:
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",
#     "https://instinto-parfums.vercel.app", # (Ejemplo de tu futuro dominio)
# ]

# --- CONFIGURACIÓN DE DRF (Tokens) ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# En backend/settings.py

# Permite que el Frontend le hable al Backend
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://frontend-instinto.onrender.com",  # <-- TU URL DEL FRONTEND
]

# Permite enviar formularios (como el Login) desde esa URL
CSRF_TRUSTED_ORIGINS = [
    "https://frontend-instinto.onrender.com",  # <-- TU URL DEL FRONTEND
    "https://backend-instinto.onrender.com",   # <-- TU URL DEL BACKEND
]